@api_HostAddress = http://localhost:5000
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjNiMDk1NzQ3YmY4MzMxZWE0YWQ1M2YzNzBjNjMyNjAxNzliMGQyM2EiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiY2hhZmlhYXlhIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2RlbW9iYXNlLTQxYzU5IiwiYXVkIjoiZGVtb2Jhc2UtNDFjNTkiLCJhdXRoX3RpbWUiOjE3NzY5ODk5NjAsInVzZXJfaWQiOiJQS3ZSZGFBZWV3WnRmd0VpWWgxSGZkUENnV2kxIiwic3ViIjoiUEt2UmRhQWVld1p0ZndFaVloMUhmZFBDZ1dpMSIsImlhdCI6MTc3Njk4OTk2MCwiZXhwIjoxNzc2OTkzNTYwLCJlbWFpbCI6ImNoYWZpYWF5QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJjaGFmaWFheUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.yCS5NIEm1A8Jz7gwBsLAv0ECSheMSXPLctTejePGvMDxy259Rtc6AYAek68WKbOBengq2gng4lYodoo2fcR0gEFRQHIwquYK_qmpMkQJfSabYCozXvB0fgg8nvNxbfbTneG3JQwNl5rLo1Pwvc9qMesEYlKLgtYsAAOjgtzv9TwWspEPNvtNP_lqOOaRCaH6qqSR8oKDz9kk4iENQQXuZMrHGAPTVp9vyQsAx774-PUpbu7Ixo40yhY0oegkflzxr7EcUED1opUioo8A3xxixiaT2UUABx6DsHkH5lG8mJ18PVbfDxvMx-6WqS0j-i1qdFodyc-hxeRgl1qxKfTRmg
POST {{api_HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
    "name":"chafiaayap",
    "password":"123456789",
    "email": "chafiaayao@gmail.com"
}
###
POST {{api_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "password":"12345678",
    "email": "chafiaay@gmail.com"
}
###
POST {{api_HostAddress}}/auth/refresh
Accept: application/json
Content-Type: application/json

{
    "refreshToken":"AMf-vBxtIrFXEUEfXh2dGD-NvYex_O5CreFiY9ORGQqV9tDsdgZFJdx04PxyrRPLQs4VhhEZ2AtaBuLdmLw325Yle-_QAl-2Y-AaGfMKQ4xPt5TVke_KYeaBm5uRtJqJ0f5snMkibyhZvjNzc5peaQAoQt9MmOCVmDTUdgHhgY7mNgE5d-L9_BnCDa7R63NglTtUV-EG0LJDgUt8HDH-QdO1qbYAomufWQ"
}
###
POST {{api_HostAddress}}/auth/logout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
