@api_HostAddress = http://localhost:5000
POST {{api_HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
    "name":"chafiaayap",
    "password":"123456789",
    "email": "chafiaayao@gmail.com"
}
###
POST {{api_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "password":"12345678",
    "email": "chafiaay@gmail.com"
}